// ==UserScript==
// @name         Sentinel Mobile — FRED RC5 Persistence Probe
// @namespace    Sentinel
// @version      1.0.0-rc5
// @description  FRED PDA compatibility probe: persistence, cleanup, re-entry and optional chaining
// @author       Sentinel
// @match        https://www.torn.com/*
// @grant        none
// ==/UserScript==
(function(){'use strict';const VERSION='1.0.0-rc5';const STORE_KEY='sentinel.fred.rc5';const ROOT_ID='fred-rc5-root';const NOW=()=>Math.floor(Date.now()/1000);function emptyState(){return{schema:1,ui:{open:false},operational:{launches:0,lastLaunchAt:0,lastTapAt:0}}}function loadState(){try{const raw=localStorage.getItem(STORE_KEY);if(!raw)return emptyState();const p=JSON.parse(raw);return{...emptyState(),...p,ui:{...emptyState().ui,...(p.ui||{})},operational:{...emptyState().operational,...(p.operational||{})}}}catch(_){return emptyState()}}let state=loadState();function saveState(){try{localStorage.setItem(STORE_KEY,JSON.stringify(state))}catch(_){}}function b(t){let e=document.getElementById('fred-boot-trace');if(!e){e=document.createElement('div');e.id='fred-boot-trace';e.style.cssText='position:fixed;right:12px;bottom:90px;z-index:2147483647;background:#171b22;color:#fff;border:1px solid #4d5968;border-radius:8px;padding:10px 14px;font:700 14px -apple-system,BlinkMacSystemFont,Segoe UI,Arial,sans-serif;box-shadow:0 2px 12px rgba(0,0,0,.55)';document.body.appendChild(e)}e.textContent=t}function render(){let root=document.getElementById(ROOT_ID);if(!root){root=document.createElement('div');root.id=ROOT_ID;root.style.cssText='position:fixed;left:7px;top:48%;z-index:2147483647';document.body.appendChild(root)}root.innerHTML='<button id="fred-rc5-launcher" style="width:34px;height:34px;border:0;border-radius:9px;background:#171b22;color:#2f82ff;font-weight:900">S</button>';root.querySelector('#fred-rc5-launcher')?.addEventListener('click',()=>{state.ui.open=!state.ui.open;state.operational.lastTapAt=NOW();saveState();b('FRED RC5 TAP OK • launches '+state.operational.launches+' • saved '+state.operational.lastTapAt)})}function init(){b('FRED RC5 3 — INIT');try{if(window.__SENTINEL_FRED_RC5_RUNNING__){try{window.__SENTINEL_FRED_RC5_RUNNING__.destroy()}catch(_){}}document.getElementById(ROOT_ID)?.remove();const controller={destroy(){document.getElementById(ROOT_ID)?.remove()}};window.__SENTINEL_FRED_RC5_RUNNING__=controller;state.operational.launches=Number(state.operational.launches||0)+1;state.operational.lastLaunchAt=NOW();saveState();b('FRED RC5 4 — PERSISTED • launch '+state.operational.launches);render();b('FRED RC5 5 — LAUNCHER • launch '+state.operational.launches)}catch(e){b('FRED RC5 ERROR — '+String(e?.message||e))}}function start(){b('FRED RC5 2 — STATE');if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()}if(document.body){b('FRED RC5 1 — EXEC');start()}else document.addEventListener('DOMContentLoaded',()=>{b('FRED RC5 1 — EXEC');start()},{once:true})})();